version: '3.7'

services:
  web:
    build: .
    restart: always
    volumes:
      - ./app/:/app/app/
      - ./app/static/dist/easy_read.css:/app/static/easy_read.css
      - ./prestart.sh:/app/prestart.sh
      - ./app/static/images:/app/static/images
      - ./app/static/govuk-frontend:/app/static/govuk-frontend
      - ./server/upload.nginx:/etc/nginx/conf.d/upload.conf
    ports:
      - 5000:5000
    env_file:
      - .env.dev
    environment:
      IS_DEV: 1
      API_ENV: DEVELOPMENT
      FLASK_ENV: DEVELOPMENT
