name: Deploy Easy Read to Sandbox Environment

on:
 push:
  branches:
   - sandbox

jobs:
 deploy:
  runs-on: ubuntu-latest
  name: Deploy Easy Read to Sandbox Environment
  environment: sandbox

## declares credentials for Azure Container Registry
  steps:
  - uses: actions/checkout@v2



  - name: Login to Azure Container Registry
    uses: azure/docker-login@v1
    with:
      login-server: c19dashacrprod.azurecr.io
      username: ${{ secrets.REGISTRY_USERNAME }}
      password: ${{ secrets.REGISTRY_PASSWORD }}


  - run: |
        docker build . -t c19dashacrprod.azurecr.io/easyread-server:${{ github.run_id }}-sandbox
        docker push c19dashacrprod.azurecr.io/easyread-server:${{ github.run_id }}-sandbox 


 ## Deploys to the docker image to the Easy Reader App Service ###
  - name: Deploy Container to Azure App Services
    uses: azure/webapps-deploy@v2
    with:
      app-name: 'c19dashsbuksfe01easyread01'
      publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
      images: 'c19dashacrprod.azurecr.io/easyread-server:${{ github.run_id }}-sandbox'

